name: Build
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22'
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y libglib2.0-dev
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build Vinegar
      run: make
